name: driven-example
version: '0.0.0.1'
category: Web
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: 2017 Author name here
license: BSD3
github: githubuser/driven-example
extra-source-files:
- README.md
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
dependencies:
- base
- protolude
- yaml
- aeson
- etc
- unordered-containers
- bytestring
- file-embed
- driven-core
- driven-json-schema
- driven-protobuff-schema
executables:
  driven-example:
    source-dirs:
    - src
    main: Main.hs
