inputs:
- type: memory_queue
  name: mem_topic_validated
  max_size: 1000
  retry_after_ms: 120000

- type: memory_queue
  name: mem_message_queued
  max_size: 1000
  retry_after_ms: 120000

outputs:
- type: memory_queue
  name: mem_topic_validated

events:
  topic_validated:
    schema: resources/private/schema/json/topic_validated_v1.0.json
    workers:
    - input: mem_topic_validated
      timeout_ms: 3000
      count: 2

    outputs:
    - mem_topic_validated

  message_queued:
    schema: protobuffer
    workers:
    - input: mem_message_queued
      timeout_ms: 3000
      count: 2
    outputs: []
    # - type: sqs
    #   url: sqs://
    #
    # output:
    # - type: sns
    #   sns_arn: sns://...
