events:
  topic_validated:
    # schema: resources/private/schema/json/topic_validated_v1.0.json
    input:
    - type: memory_queue
      max_size: 1000
      retry_after_ms: 1000
      worker:
        timeout_ms: 3000
        count: 2

  message_queued:
    schema: resources/private/schema/json/message_queued_v1.0.json
    input:
    - type: memory_queue
      max_size: 1000
      worker:
        timeout_ms: 3000
        count: 2
    # - type: sqs
    #   url: sqs://
    #
    # output:
    # - type: sns
    #   sns_arn: sns://...
