name: driven-json-schema
version: '0.0.0.1'
category: Web
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: 2017 Roman Gonzalez
license: MIT
github: roman/Haskell-driven
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Control.Driven.Schema.JsonSchema
  dependencies:
  - base >=4.7 && <5
  - protolude
  - aeson
  - bytestring
  - text
  - hjsonschema
  - driven-core
tests:
  driven-json-schema-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - driven-json-schema
