inputs:
- type: memory_queue
  name: mem_topic_validated
  max_size: 1000
  retry_after_ms: 120000
- type: memory_queue
  name: mem_message_queued
  max_size: 1000
  retry_after_ms: 120000

outputs:
- type: memory_queue
  name: mem_topic_validated

events:
  topic_validated:
    schema:
      type: json_schema
      path: ./examples/driven-example/resources/private/schema/json/topic_validated_v1.0.json

    workers:
    - consumes: mem_topic_validated
      timeout_ms: 3000
      count: 2

    delivers: []

  message_queued:
    schema:
      type: json_schema
      path: ./examples/driven-example/resources/private/schema/json/message_queued_v1.0.json

    workers:
    - consumes: mem_message_queued
      timeout_ms: 3000
      count: 2

    delivers:
    - event: topic_validated
      output: mem_topic_validated
      optional: true
