name: driven-core
version: '0.0.0.1'
category: Test
author: Roman Gonzalez
maintainer: romanandreg@gmail.com
copyright: © 2017 Roman Gonzalez
license: MIT
github: roman/Haskell-driven
tested-with: GHC==7.10.3 GHC==8.0.1 GHC==8.0.2
extra-source-files:
- README.md
- CHANGELOG.md
ghc-options:
- -Wall
- -Werror
- -O2
dependencies:
- base >=4.8 && <5
- protolude
library:
  source-dirs: src
  exposed-modules:
  - Control.Driven
  - Control.Driven.Types
  - Control.Driven.Backend.Memory
  dependencies:
  - bytestring >=0.10 && <0.11
  - containers >=0.5 && <0.6
  - text >=1.2 && <1.3
  - unordered-containers
  - hashable
  - etc
  - aeson
  - async
  - stm-chans
  - stm
  - ghc-prim
  - SafeSemaphore
  - yaml
tests:
  driven-test:
    main: TestSuite.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - tasty-hspec
    - tasty-quickcheck
    - tasty-rerun
    - tasty-discovery
    - driven
  driven-doctest:
    main: DocTest.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - Glob
    - QuickCheck
    - driven
benchmarks:
  driven-benchmark:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - criterion
    - driven
stability: alpha (experimental)
